apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: vbg-pipeline-
  annotations: {pipelines.kubeflow.org/kfp_sdk_version: 1.0.4, pipelines.kubeflow.org/pipeline_compilation_time: '2020-11-02T22:13:42.206259',
    pipelines.kubeflow.org/pipeline_spec: '{"description": "vbg pipeline", "inputs":
      [{"default": "python run_training.py -gpu 0 -experiment_name=grachev-test",
      "name": "cmd", "optional": true, "type": "String"}, {"default": "origin/AI-177-wandb",
      "name": "GIT_BRANCH", "optional": true, "type": "String"}], "name": "vbg pipeline"}'}
  labels: {pipelines.kubeflow.org/kfp_sdk_version: 1.0.4}
spec:
  entrypoint: vbg-pipeline
  templates:
  - name: main
    container:
      args: ['{{inputs.parameters.cmd}}']
      env:
      - {name: GIT_BRANCH, value: '{{inputs.parameters.GIT_BRANCH}}'}
      image: cprc/ai:vbg
      imagePullPolicy: Always
      volumeMounts:
      - {mountPath: /data, name: data-volume}
      - {mountPath: /dev/shm, name: shm-volume}
    inputs:
      parameters:
      - {name: GIT_BRANCH}
      - {name: cmd}
    nodeSelector: {kubernetes.io/hostname: sjc02-c01-dgx01.stage.ringcentral.com}
    volumes:
    - hostPath: {path: /data/k8s, type: Directory}
      name: data-volume
    - hostPath: {path: /dev/shm, type: Directory}
      name: shm-volume
  - name: vbg-pipeline
    inputs:
      parameters:
      - {name: GIT_BRANCH}
      - {name: cmd}
    dag:
      tasks:
      - name: main
        template: main
        arguments:
          parameters:
          - {name: GIT_BRANCH, value: '{{inputs.parameters.GIT_BRANCH}}'}
          - {name: cmd, value: '{{inputs.parameters.cmd}}'}
  arguments:
    parameters:
    - {name: cmd, value: python run_training.py -gpu 0 -experiment_name=grachev-test}
    - {name: GIT_BRANCH, value: origin/AI-177-wandb}
  serviceAccountName: pipeline-runner
  imagePullSecrets:
  - {name: docker-registry}
